//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeIndexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeIndexResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinalNew.AppCode.Resources.HomeIndexResource", typeof(HomeIndexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Agentləri üçün üstünlüklər.
        /// </summary>
        public static string Agent_Advantages {
            get {
                return ResourceManager.GetString("Agent Advantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elan Üstünlüklərimiz.
        /// </summary>
        public static string Announce_Advantages {
            get {
                return ResourceManager.GetString("Announce Advantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to günlük.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öz Evini Tap.
        /// </summary>
        public static string Find_Your_Home {
            get {
                return ResourceManager.GetString("Find Your Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əlaqə.
        /// </summary>
        public static string Get_in_touch {
            get {
                return ResourceManager.GetString("Get in touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ay.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ən Çox Baxılanlar.
        /// </summary>
        public static string Most_Viewed_Homes {
            get {
                return ResourceManager.GetString("Most Viewed Homes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizim Üstünlüklərimiz.
        /// </summary>
        public static string Our_Advantages {
            get {
                return ResourceManager.GetString("Our Advantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Agentləri.
        /// </summary>
        public static string Our_Real_Estate_Agents {
            get {
                return ResourceManager.GetString("Our Real Estate Agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhşur Kateqoriyalar.
        /// </summary>
        public static string Popular_Categories {
            get {
                return ResourceManager.GetString("Popular Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizlilik və Təhlükəsizlik.
        /// </summary>
        public static string Privacy_and_Security {
            get {
                return ResourceManager.GetString("Privacy and Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elan.
        /// </summary>
        public static string properities {
            get {
                return ResourceManager.GetString("properities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ətraflı.
        /// </summary>
        public static string Read_More {
            get {
                return ResourceManager.GetString("Read More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to satış.
        /// </summary>
        public static string sale {
            get {
                return ResourceManager.GetString("sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtarış.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mövcud Adreslər.
        /// </summary>
        public static string Various_Locations {
            get {
                return ResourceManager.GetString("Various Locations", resourceCulture);
            }
        }
    }
}
