//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinalNew.AppCode.Resources.LayoutResource", typeof(LayoutResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elan Yerləşdir.
        /// </summary>
        public static string Add_Announce {
            get {
                return ResourceManager.GetString("Add Announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATIŞ AGENTLƏRİ.
        /// </summary>
        public static string Agents {
            get {
                return ResourceManager.GetString("Agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əlaqə.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sürətli əlaqələr.
        /// </summary>
        public static string Fast_links {
            get {
                return ResourceManager.GetString("Fast links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEÇİLMİŞLƏR.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail adresinizi daxil edərək abonə ola bilərsiniz və saytımızla bağlı yeniliklərdən daha tez xəbər ala bilərsiniz..
        /// </summary>
        public static string Footer_Subscribe_Description {
            get {
                return ResourceManager.GetString("Footer Subscribe Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ƏSAS SƏHİFƏ.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hər hansı bir sualınız olduqda bizimlə 24/7 email vasitəsi ilə əlaqə saxlaya bilərsiniz. Əlaqə səhifəsinə daxil olub elmail göndərə bilərsiniz. .
        /// </summary>
        public static string Layout_small_description {
            get {
                return ResourceManager.GetString("Layout small description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş/Qeydiyyat.
        /// </summary>
        public static string Login_Registration {
            get {
                return ResourceManager.GetString("Login/Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MƏNİM ELANLARIM.
        /// </summary>
        public static string My_Announces {
            get {
                return ResourceManager.GetString("My Announces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son elanlar.
        /// </summary>
        public static string Recent_announces {
            get {
                return ResourceManager.GetString("Recent announces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En yeni elanlar.
        /// </summary>
        public static string Recent_posts {
            get {
                return ResourceManager.GetString("Recent posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonə ol.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
    }
}
